In [74]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

In [75]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
file_path = Path('heart_2020_cleaned.csv')
heart_df = pd.read_csv(file_path)
heart_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

In [76]:
from sklearn.model_selection import train_test_split

In [77]:
heart_df.describe

<bound method NDFrame.describe of        HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  16.60     Yes              No     No               3
1                No  20.34      No              No    Yes               0
2                No  26.58     Yes              No     No              20
3                No  24.21      No              No     No               0
4                No  23.71      No              No     No              28
...             ...    ...     ...             ...    ...             ...
319790          Yes  27.41     Yes              No     No               7
319791           No  29.84     Yes              No     No               0
319792           No  24.24      No              No     No               0
319793           No  32.81      No              No     No               0
319794           No  46.56      No              No     No               0

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0                 30          No  Female        55-59     White      Yes
1                  0          No  Female  80 or older     White       No
2                 30          No    Male        65-69     White      Yes
3                  0          No  Female        75-79     White       No
4                  0         Yes  Female        40-44     White       No
...              ...         ...     ...          ...       ...      ...
319790             0         Yes    Male        60-64  Hispanic      Yes
319791             0          No    Male        35-39  Hispanic       No
319792             0          No  Female        45-49  Hispanic       No
319793             0          No  Female        25-29  Hispanic       No
319794             0          No  Female  80 or older  Hispanic       No

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer
0                   Yes  Very good          5    Yes            No        Yes
1                   Yes  Very good          7     No            No         No
2                   Yes       Fair          8    Yes            No         No
3                    No       Good          6     No            No        Yes
4                   Yes  Very good          8     No            No         No
...                 ...        ...        ...    ...           ...        ...
319790               No       Fair          6    Yes            No         No
319791              Yes  Very good          5    Yes            No         No
319792              Yes       Good          6     No            No         No
319793               No       Good         12     No            No         No
319794              Yes       Good          8     No            No         No

[319795 rows x 18 columns]>

In [78]:
y = heart_df['HeartDisease']
X = heart_df.drop(columns = 'HeartDisease')

In [79]:
y.head()

0    No
1    No
2    No
3    No
4    No
Name: HeartDisease, dtype: object

In [80]:
X.head()

,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No

In [81]:
y.value_counts()

No     292422
Yes     27373
Name: HeartDisease, dtype: int64

In [82]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [118]:
categorical_columns = [name for name in heart_df.columns if heart_df[name].dtype=='O']

print(f'There are {len(categorical_columns)} categorical features:\n')
print(", ".join(categorical_columns))

feature_no_drop = ['AgeCategory', 'Diabetic', 'GenHealth']

categorical_drop_first = [name for name in categorical_columns if name not in feature_no_drop]
categorical_no_drop = [name for name in categorical_columns if name in feature_no_drop]

heart_disease_df_dummy = pd.get_dummies(data=heart_df, columns=categorical_drop_first, drop_first=True)
heart_disease_df_dummy = pd.get_dummies(data=heart_disease_df_dummy, columns=categorical_no_drop)
heart_disease_df_dummy.head(5)

There are 13 categorical features:

Smoking, AlcoholDrinking, Stroke, DiffWalking, Sex, AgeCategory, Race, Diabetic, PhysicalActivity, GenHealth, Asthma, KidneyDisease, SkinCancer

,HeartDisease,BMI,PhysicalHealth,MentalHealth,SleepTime,Smoking_Yes,AlcoholDrinking_Yes,Stroke_Yes,DiffWalking_Yes,Sex_Male,...,AgeCategory_80 or older,Diabetic_No,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy),GenHealth_Excellent,GenHealth_Fair,GenHealth_Good,GenHealth_Poor,GenHealth_Very good
0,0,16.60,3.0,30.0,5.0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1,0,20.34,0.0,0.0,7.0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,1
2,0,26.58,20.0,30.0,8.0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
3,0,24.21,0.0,0.0,6.0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,0,23.71,28.0,0.0,8.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1

In [119]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  int64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 43.9+ MB

In [120]:
heart_df["PhysicalHealth"] = heart_df["PhysicalHealth"].astype(float)
heart_df["MentalHealth"] = heart_df["MentalHealth"].astype(float)
heart_df["SleepTime"] = heart_df["SleepTime"].astype(float)

In [121]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  int64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 43.9+ MB

In [122]:
heart_df["HeartDisease"] = heart_df["HeartDisease"].replace({"Yes": 1, "No": 0})

In [123]:
columns_with_no = heart_df.columns[heart_df.astype(str).apply(lambda x: x.str.contains('No')).any()]
print(columns_with_no)

Index(['Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Diabetic',
       'PhysicalActivity', 'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

In [124]:
heart_disease_df_dummy

,HeartDisease,BMI,PhysicalHealth,MentalHealth,SleepTime,Smoking_Yes,AlcoholDrinking_Yes,Stroke_Yes,DiffWalking_Yes,Sex_Male,...,AgeCategory_80 or older,Diabetic_No,"Diabetic_No, borderline diabetes",Diabetic_Yes,Diabetic_Yes (during pregnancy),GenHealth_Excellent,GenHealth_Fair,GenHealth_Good,GenHealth_Poor,GenHealth_Very good
0,0,16.60,3.0,30.0,5.0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1,0,20.34,0.0,0.0,7.0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,1
2,0,26.58,20.0,30.0,8.0,1,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
3,0,24.21,0.0,0.0,6.0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,0,23.71,28.0,0.0,8.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,7.0,0.0,6.0,1,0,0,1,1,...,0,0,0,1,0,0,1,0,0,0
319791,0,29.84,0.0,0.0,5.0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
319792,0,24.24,0.0,0.0,6.0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
319793,0,32.81,0.0,0.0,12.0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
319794,0,46.56,0.0,0.0,8.0,0,0,0,0,0,...,1,1,0,0,0,0,0,1,0,0

In [125]:
y = heart_disease_df_dummy['HeartDisease']
X = heart_disease_df_dummy.drop(columns = 'HeartDisease')

In [126]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [127]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model_1 = LogisticRegression(random_state=1)

model_1.fit(X_train, y_train)

/Users/jacobdarmofal/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(random_state=1)

In [128]:
y_pred = model_1.predict(X_test)

In [129]:
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head()

   Prediction  Actual
0           0       0
1           0       0
2           0       0
3           0       0
4           0       0

In [130]:
balanced_accuracy_score(y_test, y_pred)

0.5539881186178768

In [131]:
print(confusion_matrix(y_test, y_pred))

[[72421   685]
 [ 6040   803]]

In [132]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96     73106
           1       0.54      0.12      0.19      6843

    accuracy                           0.92     79949
   macro avg       0.73      0.55      0.57     79949
weighted avg       0.89      0.92      0.89     79949

In [133]:
from imblearn.over_sampling import RandomOverSampler

random_oversampler_model = RandomOverSampler(random_state = 1)

X_resample, y_resample = random_oversampler_model.fit_resample(X_train, y_train)

In [134]:
y_resample.value_counts()

0    219316
1    219316
Name: HeartDisease, dtype: int64

In [135]:
model_2 = LogisticRegression(random_state = 1)

model_2.fit(X_resample, y_resample)

y_pred_1 = model_2.predict(X_test)

/Users/jacobdarmofal/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [136]:
results_1 = pd.DataFrame({"Prediction": y_pred_1, "Actual": y_test}).reset_index(drop=True)
results_1.head()

   Prediction  Actual
0           0       0
1           0       0
2           0       0
3           0       0
4           1       0

In [137]:
balanced_accuracy_score(y_test, y_pred_1)

0.7638604297690142

In [138]:
print(confusion_matrix(y_test, y_pred_1))

[[54893 18213]
 [ 1527  5316]]

In [139]:
print(classification_report(y_test, y_pred_1))

              precision    recall  f1-score   support

           0       0.97      0.75      0.85     73106
           1       0.23      0.78      0.35      6843

    accuracy                           0.75     79949
   macro avg       0.60      0.76      0.60     79949
weighted avg       0.91      0.75      0.81     79949